.git
node_modules
.next
.next-docker
coverage
dist
*.log
.DS_Store
.env

docs
infra
misc
config

README.md
RUN.md
TODO.md
summary.md

apps/dashboard/src
apps/dashboard/app
apps/dashboard/public
apps/dashboard/README.md
apps/dashboard/render.yaml
apps/dashboard/render.staging.yaml

apps/worker/src
apps/worker/test
apps/worker/README.md
apps/worker/render.yaml
apps/worker/render.staging.yaml
